### 考点：Read Function / Write Function
**Problem 1_Midterm 2**

In [87]:
import numpy as np
import pandas as pd

def mystery_function(A,p,q):
    
    (n,m) = A.shape
    foo = False
    
    if max(p,q)>m | (p==q):
        foo = "not possible"
    else:
        foo = A[A.T[p].argsort()]
        bar = set(A.T[p])
        for x in bar:
            Ax = A[A.T[p]==x]
            foo[foo.T[p]==x] = Ax[Ax.T[q].argsort()]
    
    return foo

mystery_function(np.array([[3,1,3],[5,2,4]]), 1, 2) # n=2, m=3

array([[3, 1, 3],
       [5, 2, 4]])

The function sorts the array A first by the values in column p, and then, if there are ties in column p also by the values in column q. 

**Problem 2_Practice 2**

Write a Python program called "k_smallest" to find the kth smallest value (and it's position(s) as a array of coordinates) in a given NumPy array (of any dimension).

**Example**: X = np.array([[[3,0,3,4],[6,6,1,8],[5,3,5,0]],[[3,0,3,8],[7,3,2,7],[8,6,2,5]]]) k_smallest(X,3) = (2, array([[1, 1, 2],[1, 2, 2]]))

In [54]:
def k_smallest(array, k):
    
    val = list(set(array.flatten()))[k-1] # find the k-th smallest value
    print(list(set(array.flatten())))
    
    pos = np.argwhere(array==val)       # find the positions
    print(array==val)
    
    return (val, pos)
    
X = np.array([[[3,0,3,4],[6,6,1,8],[5,3,5,0]],[[3,0,3,8],[7,3,2,7],[8,6,2,5]]])
k_smallest(X,3)

[0, 1, 2, 3, 4, 5, 6, 7, 8]
[[[False False False False]
  [False False False False]
  [False False False False]]

 [[False False False False]
  [False False  True False]
  [False False  True False]]]


(2, array([[1, 1, 2],
        [1, 2, 2]]))

**Problem 3_Practice 2**

Write a Python function that takes as its input a two-dimensional NumPy array and returns the subset array that consist of all the even rows (second, fourth, sixth row etc.) and all the odd columns (first, third, fifth etc.). 

In [55]:
def even_odd(array):
    return array[1::2,::2]

even_odd(np.array([[3,1,3],[5,2,4]])) 
# return a sub-array consists of entries from the 2nd row, 1st&3rd columns

array([[5, 4]])

**Problem 4_Practice 2**

The following "mystery" function takes as its input a two-dimensional numerical NumPy array. Provide an example input X (X should be a two-dimensional NumPy array) for which the function returns the value 4. Your input array should not have constant entries. 

In [83]:
def mystery(array):
    print(array)
    print(array.min(axis=1))
    return array.min(axis=1).max() 

# min() 如果不特殊说明 括号内内容 则是找所有最小
# min(axis=1) 压缩到同一行 row

mystery(np.array([[[3,0,3,4],[6,6,1,8],[5,3,5,0]],[[3,0,3,8],[7,3,2,7],[8,6,2,5]]]))

[[[3 0 3 4]
  [6 6 1 8]
  [5 3 5 0]]

 [[3 0 3 8]
  [7 3 2 7]
  [8 6 2 5]]]
[[3 0 1 0]
 [3 0 2 5]]


5

**Problem 5_Practice 2**

Write a Python function that takes as its input a two-dimensional Numpy array and returns an array of the same shape in which each row is standardized (has mean 0 and variance 1). 

In [57]:
def standardize_array(array):
    X = (array - array.mean(axis=1, keepdims=True))/array.std(axis=1, keepdims = True)
    return X

standardize_array(np.array([[[3,0,3,4],[6,6,1,8],[5,3,5,0]],[[3,0,3,8],[7,3,2,7],[8,6,2,5]]]) )

array([[[-1.33630621, -1.22474487,  0.        ,  0.        ],
        [ 1.06904497,  1.22474487, -1.22474487,  1.22474487],
        [ 0.26726124,  0.        ,  1.22474487, -1.22474487]],

       [[-1.38873015, -1.22474487,  1.41421356,  1.06904497],
        [ 0.46291005,  0.        , -0.70710678,  0.26726124],
        [ 0.9258201 ,  1.22474487, -0.70710678, -1.33630621]]])

**Problem 6_Practice 2**

In [84]:
def mystery(X):
    print(~X.any(axis=0))            # return True if any True (1) inside
    print(~X.any(axis=1))
    print((~X.any(axis=0)).any())   
    print((~X.any(axis=1)).any())
    return (~X.any(axis=0)).any()|(~X.any(axis=1)).any()

mystery(np.array([[3,0,3,0],[6,6,1,0],[5,3,5,0]]))

[False False False  True]
[False False False]
True
False


True

**Answer** The function checks whether the matrix X contains at least one column or one row filled entirely with either 0 or 'False'.

**Problem 7_Practice 2**

Write a function called "SMA" that takes as its input a one-dimensional NumPy array $A$ and a window width $n$ (integer $\ge 1$) and returns a one-dimensional NumPy array of the same size as $A$, whose entries are the simple moving averages over the sliding windows. That is, for window size n, the entry $x_i$ in position i would be replaced by mean$(x_{i-n}, \ldots, x_i, \ldots, x_{i+n})$. At the beginning and end of the array the windows have to be truncated. 

Example: SMA(np.array([1,2,3,4,3,5,6]),1) should be array([1.5,2,3,3.33,4,4.66,5.5]) when rounded to two after-decimal digits. 

In [85]:
def SMA(array, n):                          # simple moving average
    output = np.zeros(len(array))           # create the same length array as A
    for i in range(len(array)):             # the entry in ith position will be replaced 
        left = max(i-n,0)                   # index left side  保证不越界
        right = min(i+1+n,len(array))       # index right side 保证不越界
        output[i]=np.mean(array[left:right])# calculate the SMA for each entry 
    return output

A = np.array([1,2,3,4,3,5,6])
np.round_(SMA(A,1),2)

array([1.5 , 2.  , 3.  , 3.33, 4.  , 4.67, 5.5 ])

**Problem 8_Practice 2**

Write a function called "top_two" that takes a Pandas series as its input, leaves the two most frequently appearing elements unchanged, and replaces all other elements with "Other". Return the result in the form of a new Pandas series object. What is the data type in your returned series? 

In [86]:
def top_two(ser):
    ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
    return ser
    
# Example
np.random.seed(10)
ser = pd.Series(np.random.randint(1, 5, [12]))

top_two(ser)


0         2
1         2
2         1
3     Other
4         1
5         2
6     Other
7         1
8         2
9         2
10        1
11        2
dtype: object

**Problem 9_Practice 2**

Write a function called "letter_count" that does the following: Take a Pandas series of string objects as the input. Assume that the strings are all individual words (no punctuation, all lower-case). Return a Pandas Data Frame that contains the following columns:
* the original words from the Series
* the count of letters in each word
* a Boolean variable that evaluates to "True" if the word contains the letter sequence "ing"

In [82]:
def letter_count(ser):
    count = [len(word) for word in ser]         # create the 'count' list 
    ing = [word.find("ing")>-1 for word in ser] # create the 'ing' list 
    df = pd.DataFrame({'word':ser, 'count':count, 'contains "ing"':ing})
    return df

letter_count(pd.Series(['something', "foo", 'bar']))

word  count  contains "ing"
0  something      9            True
1        foo      3           False
2        bar      3           False